<a href="https://colab.research.google.com/github/denifadhil/DataMining/blob/main/Preprocessing%20Data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [4]:
dataset = pd.read_csv('Data.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [5]:
print(x)

[['ale-ale' 10.0 20000.0]
 ['kopikap' nan 5000.0]
 ['frestea' 3.0 6000.0]
 ['fanta' 2.0 nan]
 ['sprite' 3.0 15000.0]
 ['tehpucuk' 4.0 16000.0]
 ['fruittea' 2.0 12000.0]
 ['LeMinerale' 5.0 50000.0]]


In [6]:
print(y)

[' yes' ' yes' ' no' 'yes' 'no' ' yes' ' no' ' yes']


In [7]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])

In [8]:
print(x)

[['ale-ale' 10.0 20000.0]
 ['kopikap' 4.142857142857143 5000.0]
 ['frestea' 3.0 6000.0]
 ['fanta' 2.0 17714.285714285714]
 ['sprite' 3.0 15000.0]
 ['tehpucuk' 4.0 16000.0]
 ['fruittea' 2.0 12000.0]
 ['LeMinerale' 5.0 50000.0]]


In [10]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [11]:
print(x)

[[0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 10.0 20000.0]
 [0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 4.142857142857143 5000.0]
 [0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 3.0 6000.0]
 [0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 2.0 17714.285714285714]
 [0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 3.0 15000.0]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 4.0 16000.0]
 [0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 2.0 12000.0]
 [1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 5.0 50000.0]]


In [12]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [13]:
print(y)

[1 1 0 3 2 1 0 1]


In [14]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 1)


In [15]:
print(x_train)

[[0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 4.142857142857143 5000.0]
 [0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 2.0 12000.0]
 [0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 10.0 20000.0]
 [0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 3.0 15000.0]
 [0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 2.0 17714.285714285714]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 4.0 16000.0]]


In [16]:
print(x_test)

[[1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 5.0 50000.0]
 [0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 3.0 6000.0]]


In [17]:
print(y_train)

[1 0 1 2 3 1]


In [18]:
print(y_test)

[1 0]


In [20]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 3:] = sc.fit_transform(x_train[:, 3:])
x_test[:, 3:] = sc.transform(x_test[:, 3:])

In [21]:
print(x_train)

[[0.0 0.0 0.0 0.0 -0.44721359549995787 2.2360679774997894
  -0.44721359549995787 -0.44721359549995787 -0.01742625780188706
  -1.9271070484863606]
 [0.0 0.0 0.0 0.0 2.2360679774997894 -0.44721359549995787
  -0.44721359549995787 -0.44721359549995787 -0.8016078588868077
  -0.47436481193510394]
 [0.0 1.0 0.0 0.0 -0.44721359549995787 -0.44721359549995787
  -0.44721359549995787 -0.44721359549995787 2.1260034518302287
  1.1859120298377608]
 [0.0 0.0 0.0 0.0 -0.44721359549995787 -0.44721359549995787
  2.2360679774997894 -0.44721359549995787 -0.43565644504717815
  0.14823900372972032]
 [0.0 0.0 1.0 0.0 -0.44721359549995787 -0.44721359549995787
  -0.44721359549995787 -0.44721359549995787 -0.8016078588868077
  0.7115472179026564]
 [0.0 0.0 0.0 0.0 -0.44721359549995787 -0.44721359549995787
  -0.44721359549995787 2.2360679774997894 -0.06970503120754856
  0.3557736089513284]]


In [23]:
print(x_test)

[[1.0 0.0 0.0 0.0 -0.44721359549995787 -0.44721359549995787
  -0.44721359549995787 -0.44721359549995787 0.296246382632081
  7.411950186486004]
 [0.0 0.0 0.0 1.0 -0.44721359549995787 -0.44721359549995787
  -0.44721359549995787 -0.44721359549995787 -0.43565644504717815
  -1.7195724432647523]]
